package moduloIDF;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nicoyarce
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private FileNameExtensionFilter filtro;

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        tituloLabel = new javax.swing.JLabel();
        iddLabel = new javax.swing.JLabel();
        idfLabel = new javax.swing.JLabel();
        epwLabel = new javax.swing.JLabel();
        botonOptimizar = new javax.swing.JButton();
        iddField = new javax.swing.JTextField();
        idfField = new javax.swing.JTextField();
        epwField = new javax.swing.JTextField();
        boton1Carga = new javax.swing.JButton();
        boton2Carga = new javax.swing.JButton();
        boton3Carga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto");

        tituloLabel.setText("Seleccione archivos");

        iddLabel.setText("IDD");

        idfLabel.setText("IDF");

        epwLabel.setText("EPW");

        botonOptimizar.setText("Optimizar");

        iddField.setText("jTextField1");

        idfField.setText("jTextField2");
        idfField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfFieldActionPerformed(evt);
            }
        });

        epwField.setText("jTextField3");

        boton1Carga.setText("...");
        boton1Carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1CargaActionPerformed(evt);
            }
        });

        boton2Carga.setText("...");
        boton2Carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2CargaActionPerformed(evt);
            }
        });

        boton3Carga.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iddLabel)
                            .addComponent(epwLabel)
                            .addComponent(idfLabel))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(iddField)
                            .addComponent(idfField)
                            .addComponent(epwField)
                            .addComponent(botonOptimizar, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton1Carga)
                    .addComponent(boton2Carga)
                    .addComponent(boton3Carga))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddLabel)
                    .addComponent(iddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton1Carga))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idfLabel)
                    .addComponent(idfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton2Carga))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epwLabel)
                    .addComponent(epwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton3Carga))
                .addGap(18, 18, 18)
                .addComponent(botonOptimizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idfFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfFieldActionPerformed

    private void boton1CargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1CargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton1CargaActionPerformed

    private void boton2CargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2CargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton2CargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Carga;
    private javax.swing.JButton boton2Carga;
    private javax.swing.JButton boton3Carga;
    private javax.swing.JButton botonOptimizar;
    private javax.swing.JTextField epwField;
    private javax.swing.JLabel epwLabel;
    private javax.swing.JTextField iddField;
    private javax.swing.JLabel iddLabel;
    private javax.swing.JTextField idfField;
    private javax.swing.JLabel idfLabel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

}
